# # This workflow uses actions that are not certified by GitHub.
# # They are provided by a third-party and are governed by
# # separate terms of service, privacy policy, and support
# # documentation.

# # GitHub recommends pinning actions to a commit SHA.
# # To get a newer version, you will need to update the SHA.
# # You can also reference a tag or branch, but the action may change without warning.

# name: Build and deploy Python app to Azure Web App

# env:
#   #AZURE_WEBAPP_NAME: MY_WEBAPP_NAME   # set this to your application's name
#   PYTHON_VERSION: '3.11'               # set this to the Python version to use

on:
  push:
    branches:
      - main

#   pull_request:
#     branches:
#       - main
      
permissions:
  contents: write
  pages: write 
  id-token: write
  pull-requests: write

jobs:
  build-and-push-image:
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        environment:
         - dev
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4

      - name: OIDC Login to Azure Public Cloud 
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
      
      - name: Build and push image
        id: build-image
        run: |
          az acr build --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/streamlitapp:${{ github.sha }} --registry ${{ secrets.REGISTRY_LOGIN_SERVER }} --file "Dockerfile" .